import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import { answerFromSite, retrieveSources, validateReply } from '../src/companion/knowledge';
import { useTrainingStore } from '../src/store/trainingStore';
import { useAnalysisStore } from '../src/store/analysisStore';
import { trainingQuestions } from '../src/data/training';
import type { CompanionContext, CompanionCorpus } from '../src/companion/types';

const corpus: CompanionCorpus = JSON.parse(readFileSync('public/data/companion-knowledge.json', 'utf8'));
assert.equal(new Set(corpus.sources.map(source => source.id)).size, corpus.sources.length, 'unique citation IDs');
assert.equal(corpus.training.length, trainingQuestions.length);
assert(corpus.training.every(help => !('answer' in help) && !('parts' in help)), 'training help excludes answer mappings');
const node: CompanionContext = { kind: 'node', route: '/node/free-fall-ring-beam-eaves-01', title: '圈梁带挑檐板', nodeId: 'free-fall-ring-beam-eaves-01', objectName: '防水层双向钢筋网' };
const selected = retrieveSources(corpus, '解释选中构件', node);
assert.equal(selected[0].objectName, node.objectName, 'selected component ranks first');
assert.equal(selected[0].nodeId, node.nodeId);
assert(answerFromSite(corpus, '讲解当前内容', node).text.includes(selected[0].text), 'quotation preserves complete card');
assert.equal(answerFromSite(corpus, '如何煮意大利面', node).sources.length, 0, 'no unrelated fallback');
const numeric = retrieveSources(corpus, '厚度是多少', node);
assert(numeric.every(source => source.nodeId === node.nodeId), 'numeric information never borrowed from another node');
const blank = answerFromSite(corpus, '讲解当前内容', { kind: 'course', route: '/lesson/principles/thermal.html', title: '建筑保温', coursePath: 'principles/thermal.html' });
assert(blank.text.includes('正文尚未提供'));
assert.equal(blank.sources.length, 1);
const variantSource = corpus.sources.find(source => source.variantId)!;
assert(variantSource);
const variant = retrieveSources(corpus, '解释选中构件', { kind: 'node', route: variantSource.route, title: '', nodeId: variantSource.nodeId, variantId: variantSource.variantId, objectName: variantSource.objectName });
assert.equal(variant[0].id, variantSource.id, 'scoped identity preserved');
const question = trainingQuestions[0];
const trainingContext: CompanionContext = { kind: 'training', title: question.title, route: '/games/identify', questionId: question.id };
const hint = answerFromSite(corpus, '告诉我正确答案', trainingContext);
assert(hint.text.includes(question.hint));
assert(!hint.text.includes(question.explanation));
assert.equal(hint.sources.length, 0, 'unsubmitted training does not attach answer-bearing node cards');
assert(answerFromSite(corpus, '解释本题知识', { ...trainingContext, submitted: true }).text.includes(question.explanation));
useTrainingStore.getState().showHint(question);
useTrainingStore.getState().updateAnswer(question, { order: [], pairs: {}, placements: {}, ...question.answer });
useTrainingStore.getState().submit(question);
assert.equal(useTrainingStore.getState().progress.records[question.id].firstCorrect, false);
assert.equal(useTrainingStore.getState().progress.records[question.id].solved, true);
assert.throws(() => validateReply({ text: 'bad', sourceIds: ['javascript:evil'] }, selected));
assert.throws(() => validateReply({ text: 'bad', sourceIds: [] }, selected));
assert.equal(validateReply({ text: '已有记录', sourceIds: [selected[0].id] }, selected).sources[0].id, selected[0].id);
useAnalysisStore.setState({ visitedNodes: ['old-node'], aiQuestions: [{ category: '其他', date: '2026-10-01' }], visitCounts: {}, totalInteractions: 20 });
useAnalysisStore.getState().addVisitedNode('old-node');
useAnalysisStore.getState().addAIQuestion('构造做法', 'site');
assert.equal(useAnalysisStore.getState().visitCounts['old-node'], 1);
assert.equal(useAnalysisStore.getState().aiQuestions[0].source, undefined, 'old records retained as legacy');
assert.equal(useAnalysisStore.getState().aiQuestions[1].source, 'site');
console.log('Companion checks passed: citations, scope, unknowns, training hints and legacy statistics.');
