import assert from 'node:assert/strict';
import { chromium } from 'playwright';
import { mkdir, writeFile } from 'node:fs/promises';
const base = process.env.COMPANION_TEST_URL ?? 'http://127.0.0.1:5173/';
const out = 'tmp/companion-browser';
await mkdir(out, { recursive: true });
const browser = await chromium.launch({ headless: true });
const errors = [];
try {
  const context = await browser.newContext({ viewport: { width:1440,height:1000 } });
  const page = await context.newPage();
  page.on('pageerror', error => errors.push(error.message));
  await page.goto(`${base}#/`);
  await page.locator('.node-model-stage[data-model-ready=true]').waitFor({timeout:45000});
  await page.evaluate(() => { window.__originalHomeCanvas = document.querySelector('.node-model-stage canvas'); });
  await page.getByRole('button', {name:'打开构造伙伴',exact:true}).click();
  await page.getByRole('button', {name:'讲解当前内容',exact:true}).click();
  await page.locator('.companion-message.is-assistant').waitFor();
  assert((await page.locator('.companion-context').innerText()).includes('蓄水屋面'));
  assert(await page.locator('.companion-sources a').count() > 0);
  await page.screenshot({path:`${out}/desktop-home.png`});
  await page.getByRole('button', {name:'关闭问答面板',exact:true}).click();
  await page.getByRole('button', {name:'下一个模型',exact:true}).click();
  await page.getByRole('button', {name:'打开构造伙伴',exact:true}).click();
  assert((await page.locator('.companion-context').innerText()).includes('有组织排水'));
  await page.goto(`${base}#/node/free-fall-ring-beam-eaves-01`);
  await page.locator('.node-viewport canvas').waitFor();
  await page.evaluate(async () => {
    window.__testNodeStore = (await import('/src/store/nodeStore.ts')).useNodeStore;
    window.__testNodeStore.getState().setSelectedObject('防水层双向钢筋网');
  });
  await page.getByRole('button', {name:'解释选中构件',exact:true}).click();
  await page.waitForFunction(() => document.querySelectorAll('.companion-message.is-assistant').length === 2);
  assert((await page.locator('.companion-message.is-assistant').last().innerText()).includes('双向钢筋网'));
  const resetBefore = await page.evaluate(() => window.__testNodeStore.getState().refitToken);
  await page.getByRole('textbox', {name:'向构造伙伴提问'}).fill('R');
  await page.getByRole('textbox', {name:'向构造伙伴提问'}).press('r');
  assert.equal(await page.evaluate(() => window.__testNodeStore.getState().refitToken), resetBefore);
  await page.keyboard.press('Escape');
  assert.equal(await page.evaluate(() => window.__testNodeStore.getState().selectedObject), '防水层双向钢筋网');
  assert(await page.locator('.companion-panel').isHidden());
  const pet = await page.locator('.companion-launcher').boundingBox();
  await page.mouse.move(pet.x + pet.width / 2, pet.y + 20);
  await page.mouse.down();
  await page.mouse.move(110, 240, {steps:8});
  await page.mouse.up();
  assert((await page.locator('.companion-launcher').boundingBox()).x < 30, 'pet docks to nearest edge');
  assert(await page.locator('.companion-panel').isHidden(), 'drag does not open chat');
  await page.goto(`${base}#/lesson/principles/thermal.html`);
  await page.waitForFunction(() => document.querySelector('.curriculum-frame')?.contentDocument?.querySelector('h1'));
  await page.getByRole('button', {name:'打开构造伙伴',exact:true}).click();
  await page.getByRole('button', {name:'讲解当前内容',exact:true}).click();
  await page.waitForFunction(() => document.querySelectorAll('.companion-message.is-assistant').length === 3);
  assert((await page.locator('.companion-message.is-assistant').last().innerText()).includes('正文尚未提供'));
  await page.goto(`${base}#/curriculum/cases/farnsworth-house?topic=windows`);
  await page.getByRole('button', {name:'讲解当前内容',exact:true}).click();
  await page.waitForFunction(() => document.querySelectorAll('.companion-message.is-assistant').length === 4);
  assert((await page.locator('.companion-message.is-assistant').last().innerText()).includes('玻璃围护'));
  await page.goto(`${base}#/games/identify?question=identify-gutter`);
  await page.getByRole('button', {name:'给我一点学习提示',exact:true}).click();
  await page.waitForFunction(() => document.querySelectorAll('.companion-message.is-assistant').length === 5);
  assert((await page.locator('.companion-message.is-assistant').last().innerText()).includes('先观察'));
  await page.evaluate(async () => {
    const store = (await import('/src/store/trainingStore.ts')).useTrainingStore;
    const question = (await import('/src/data/training.ts')).trainingQuestions.find(question => question.id === 'identify-gutter');
    if (!store.getState().progress.drafts[question.id].hinted) throw new Error('AI hint not recorded');
    store.getState().updateAnswer(question, {order:[],pairs:{},placements:{},...question.answer});
    store.getState().submit(question);
    if (store.getState().progress.records[question.id].firstCorrect) throw new Error('Assisted answer counted independent');
  });
  await page.getByRole('button', {name:'解释本题知识',exact:true}).waitFor();
  await page.goto(`${base}#/`);
  assert(await page.evaluate(() => document.querySelector('.node-model-stage canvas') === window.__originalHomeCanvas), 'homepage canvas remains mounted across routes');
  await page.getByRole('button', {name:'关闭问答面板',exact:true}).click();
  await page.locator('#sidebar-toggle').click();
  await page.goto(`${base}#/ai-extend`);
  await page.locator('.companion-intro-copy button').click();
  assert.equal(await page.locator('.companion-message.is-assistant').count(), 5, 'conversation persists');
  await page.getByRole('button', {name:'伙伴设置',exact:true}).click();
  await page.getByRole('button', {name:'隐藏伙伴',exact:true}).click();
  assert(await page.locator('.companion-root').isHidden());
  await page.locator('.companion-intro-copy button').click();
  assert(await page.locator('.companion-panel').isVisible());
  await page.goto(`${base}#/`);
  assert(await page.locator('.app').evaluate(element => element.classList.contains('sidebar-collapsed')));
  await page.locator('#modules').evaluate(element => element.scrollIntoView({block:'start'}));
  await page.waitForFunction(() => document.querySelector('.companion-context')?.textContent.includes('构造基础'));
  await page.evaluate(() => window.scrollTo({top:0,behavior:'instant'}));
  await page.waitForFunction(() => document.querySelector('.companion-context')?.textContent.includes('有组织排水'));
  await context.close();

  const mobile = await browser.newContext({viewport:{width:390,height:844},isMobile:true,hasTouch:true});
  const phone = await mobile.newPage();
  phone.on('pageerror', error => errors.push(error.message));
  await phone.goto(`${base}#/ai-extend`);
  await phone.locator('.companion-launcher').click();
  await phone.getByRole('textbox',{name:'向构造伙伴提问'}).fill('讲解屋面排水');
  await phone.getByRole('button',{name:'发送问题',exact:true}).click();
  await phone.locator('.companion-message.is-assistant').waitFor();
  const bounds = await phone.locator('.companion-panel').boundingBox();
  assert(bounds.x >= 0 && bounds.x + bounds.width <= 391 && bounds.y >= 0 && bounds.y + bounds.height <= 845);
  assert.equal(await phone.evaluate(() => document.documentElement.scrollWidth > innerWidth + 1), false);
  await phone.screenshot({path:`${out}/mobile-chat.png`});
  await phone.getByRole('button',{name:'关闭问答面板',exact:true}).click();
  await phone.goto(`${base}#/`);
  await phone.locator('#mobile-menu-toggle').click();
  assert(await phone.locator('.companion-root').isHidden(), 'companion yields to mobile navigation');
  await phone.locator('#mobile-nav-close').click();
  await phone.getByRole('button',{name:'打开构造伙伴',exact:true}).waitFor();
  await phone.getByRole('button',{name:'打开构造伙伴',exact:true}).click();
  await phone.locator('#mobile-menu-toggle').click();
  await phone.keyboard.press('Escape');
  assert.equal(await phone.evaluate(() => document.body.classList.contains('mobile-nav-open')), false, 'Escape goes to active mobile navigation');
  assert(await phone.locator('.companion-panel').isVisible(), 'chat returns after navigation closes');
  await mobile.close();
  const emptyContext = await browser.newContext();
  const dataPage = await emptyContext.newPage();
  await dataPage.goto(`${base}#/data`);
  await dataPage.getByRole('heading',{name:'快去探索节点吧'}).waitFor();
  assert.equal(await dataPage.evaluate(() => localStorage.getItem('construction-analysis')), null, 'statistics page creates no fake activity');
  await emptyContext.close();
  assert.deepEqual(errors, []);
  await writeFile(`${out}/results.json`, JSON.stringify({passed:true,errors,checks:['context and homepage sections','iframe','training independent score','R/Escape','persistent canvas/sidebar/conversation','hide/restore','mobile bounds/navigation']},null,2));
  console.log('Companion browser regression passed.');
} finally { await browser.close(); }
